package crowchiper:plugin;

world plugin {
    record plugin-config {
        name: string,
        version: string,
        hooks: list<string>,
    }

    export config: func(config: list<tuple<string, string>>) -> plugin-config;
}
